import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import FloatingChatBubble from "src/app/components/chat/FloatingChatBubble";
import SiteContentProvider from "src/app/components/cms/SiteContentProvider";
import ThemeRuntime from "src/app/components/cms/ThemeRuntime";
import { getPublicSiteContent } from "src/utils/getPublicSiteContent";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const siteContent = await getPublicSiteContent();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SiteContentProvider initialContent={siteContent}>
          <ThemeRuntime />
          {children}
          <FloatingChatBubble />
        </SiteContentProvider>
      </body>
    </html>
  );
}
