create table if not exists public.accompanist_artist_permissions (
  id bigint generated by default as identity primary key,
  accompanist_user_id bigint not null,
  artist_user_id bigint not null,
  can_add_artworks boolean not null default false,
  can_edit_artworks boolean not null default false,
  can_use_chat boolean not null default false,
  can_edit_profile_pic boolean not null default false,
  can_edit_username boolean not null default false,
  can_edit_about_me boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (accompanist_user_id, artist_user_id)
);

create index if not exists accompanist_artist_permissions_accompanist_idx
  on public.accompanist_artist_permissions (accompanist_user_id);

create index if not exists accompanist_artist_permissions_artist_idx
  on public.accompanist_artist_permissions (artist_user_id);

create or replace function public.set_accompanist_artist_permissions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_accompanist_artist_permissions_updated_at
on public.accompanist_artist_permissions;

create trigger trg_accompanist_artist_permissions_updated_at
before update on public.accompanist_artist_permissions
for each row execute function public.set_accompanist_artist_permissions_updated_at();
