-- Admin password change audit log
-- Run this in the Supabase SQL editor.

create table if not exists public.admin_password_change_logs (
  id bigint generated by default as identity primary key,
  target_user_email text null,
  changed_by_email text null,
  changed_at timestamptz not null default timezone('utc', now())
);

create index if not exists admin_password_change_logs_changed_at_idx
  on public.admin_password_change_logs (changed_at desc);
