create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  display_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists admin_users_email_idx
  on public.admin_users (email);

-- Example insert (replace the hash with your own bcrypt hash):
-- insert into public.admin_users (email, password_hash, display_name)
-- values ('admin@example.com', '$2b$12$replace-with-bcrypt-hash', 'Site Admin');
