create table if not exists public.artist_profile_change_requests (
  id bigint generated by default as identity primary key,
  artist_user_id bigint not null unique,
  proposed_username text null,
  proposed_about_me text null,
  proposed_profile_pic text null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists artist_profile_change_requests_artist_user_id_idx
  on public.artist_profile_change_requests (artist_user_id);

create or replace function public.set_artist_profile_change_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_artist_profile_change_requests_updated_at
on public.artist_profile_change_requests;

create trigger trg_artist_profile_change_requests_updated_at
before update on public.artist_profile_change_requests
for each row execute function public.set_artist_profile_change_requests_updated_at();
